name: "Main"

on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - "main"

jobs:

  test-job:
    name: "Test"
    uses: "./.github/workflows/test.yml"
