name: "Test .NET solution"

on:
  workflow_call:

jobs:

  test-extract-job:
    name: "Extract FFI: ${{ matrix.platform.name }}"
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: windows, os: windows-latest }
        - { name: linux, os: ubuntu-latest }
        - { name: macos, os: macos-latest }
    defaults:
      run:
        shell: bash
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@v4

    - name: "Install Clang: Windows"
      if: matrix.platform.os == 'windows-latest'
      run: |
        source "${{ github.workspace }}\.github\scripts\install-clang-x64-windows.sh"

    - name: "Install Clang: Linux"
      if: matrix.platform.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install gcc-i686-linux-gnu gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu llvm-14 clang-14

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: "Test .NET extract"
      run: |
        dotnet test '${{ github.workspace }}/src/cs/tests/c2ffi.Tests.EndToEnd.Extract/c2ffi.Tests.EndToEnd.Extract.csproj' --nologo --verbosity minimal --configuration Release

    - name: "Upload generated FFI files"
      uses: actions/upload-artifact@v4
      with:
        name: "ffi-${{ matrix.platform.name }}"
        path: |
          ${{ github.workspace }}/src/c/tests/**/ffi/*.json

  test-merge-job:
    name: "Merge FFIs"
    runs-on: ubuntu-latest
    needs: [test-extract-job]
    defaults:
      run:
        shell: bash
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: "Download generated FFI files: windows"
      uses: actions/download-artifact@v4
      with:
        name: "ffi-windows"
        path: |
          ${{ github.workspace }}/src/c/tests

    - name: "Download generated FFI files: linux"
      uses: actions/download-artifact@v4
      with:
        name: "ffi-linux"
        path: |
          ${{ github.workspace }}/src/c/tests

    - name: "Download generated FFI files: macos"
      uses: actions/download-artifact@v4
      with:
        name: "ffi-macos"
        path: |
          ${{ github.workspace }}/src/c/tests

    - name: "Test .NET merge"
      run: |
        dotnet test '${{ github.workspace }}/src/cs/tests/c2ffi.Tests.EndToEnd.Merge/c2ffi.Tests.EndToEnd.Merge.csproj' --nologo --verbosity minimal --configuration Release

    - name: "Upload generated FFI files"
      uses: actions/upload-artifact@v4
      with:
        name: "ffi-x"
        path: |
          ${{ github.workspace }}/src/c/tests/**/ffi-x/*.json

